server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.wasm\.gz$ {
        add_header Content-Encoding gzip;
        default_type application/wasm;
    }

    location ~ \.js\.gz$ {
        add_header Content-Encoding gzip;
        default_type application/javascript;
    }

    location ~ \.data\.gz$ {
        add_header Content-Encoding gzip;
        default_type application/octet-stream;
    }
}
